# Generated by Django 4.1.2 on 2022-11-02 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.CharField(default=datetime.datetime.now, max_length=100),
        ),
    ]
